In [47]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\Users\ANIK0101\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\Users\ANIK0101\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ANIK0101\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\ANIK0101\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\ANIK0101\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### importing neccessary libraries

In [48]:
import pandas as pd
import numpy as np

### Loading the dataset (Unclean)

In [49]:
df = pd.read_csv("./employee_data.csv")
df

,Emp_ID,Name,Age,Salary (INR),Experience (Years),City,Department,Performance Rating
0,101,Amit Sharma,27,650000.0,4.0,Delhi,IT,4.5
1,102,Riya Gupta,32,NaN,8.0,Mumbai,HR,3.8
2,103,Rajesh Verma,45,1200000.0,inf,Bangalore,Finance,4.9
3,104,Priya Singh,29,720000.0,6.0,Kolkata,IT,4.2
4,105,Sunil Kumar,26,500000.0,3.0,Chennai,Sales,NaN
5,106,Alok Mehta,52,2000000.0,28.0,Hyderabad,Operations,5.0
6,107,Kavita Yadav,31,inf,10.0,Pune,IT,4.0
7,108,Pankaj Mishra,24,-45000.0,2.0,Jaipur,Marketing,3.5
8,109,Deepika Reddy,48,3000000.0,30.0,Bangalore,Management,5.0
9,110,Ramesh Patil,29,720000.0,6.0,Kolkata,IT,4.2
10,111,Meera Nair,34,820000.0,9.0,Kochi,HR,4.3
11,112,Sameer Desai,37,1100000.0,15.0,Delhi,Finance,4.8
12,113,Swati Joshi,29,650000.0,5.0,Mumbai,IT,4.6
13,114,Vinod Iyer,55,5000000.0,35.0,Chennai,Management,5.0
14,115,Anjali Saxena,23,380000.0,1.0,Pune,HR,3.9
15,116,Manish Khanna,40,1250000.0,18.0,Hyderabad,Operations,4.7
16,117,Arjun Pandey,31,750000.0,7.0,Jaipur,IT,4.4
17,118,Neha Kapoor,28,NaN,4.0,Bangalore,IT,3.8
18,119,Amit Sharma,27,650000.0,4.0,Delhi,IT,4.5
19,120,Rohit Bansal,36,980000.0,12.0,Mumbai,Finance,4.9

### Checking the missing values
#### Missing values in each column

In [50]:
df.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Salary (INR)          2
Experience (Years)    0
City                  0
Department            0
Performance Rating    1
dtype: int64

## When Data Cleaning Completed Successfully

In [51]:
df_new = pd.read_csv("./Cleaned_Employee_Data.csv")
df_new

,Emp_ID,Name,Age,Salary (INR),Experience (Years),City,Department,Performance Rating
0,101,Amit Sharma,27,650000.0,4.000000,Delhi,IT,4.5
1,102,Riya Gupta,32,1273125.0,8.000000,Mumbai,HR,3.8
2,103,Rajesh Verma,45,1200000.0,10.894737,Bangalore,Finance,4.9
3,104,Priya Singh,29,720000.0,6.000000,Kolkata,IT,4.2
4,105,Sunil Kumar,26,500000.0,3.000000,Chennai,Sales,4.5
5,106,Alok Mehta,52,2000000.0,28.000000,Hyderabad,Operations,5.0
6,107,Kavita Yadav,31,1273125.0,10.000000,Pune,IT,4.0
7,108,Pankaj Mishra,24,1273125.0,2.000000,Jaipur,Marketing,3.5
8,109,Deepika Reddy,48,3000000.0,30.000000,Bangalore,Management,5.0
9,110,Ramesh Patil,29,720000.0,6.000000,Kolkata,IT,4.2
10,111,Meera Nair,34,820000.0,9.000000,Kochi,HR,4.3
11,112,Sameer Desai,37,1100000.0,15.000000,Delhi,Finance,4.8
12,113,Swati Joshi,29,650000.0,5.000000,Mumbai,IT,4.6
13,115,Anjali Saxena,23,380000.0,1.000000,Pune,HR,3.9
14,116,Manish Khanna,40,1250000.0,18.000000,Hyderabad,Operations,4.7
15,117,Arjun Pandey,31,750000.0,7.000000,Jaipur,IT,4.4
16,118,Neha Kapoor,28,1273125.0,4.000000,Bangalore,IT,3.8
17,119,Amit Sharma,27,650000.0,4.000000,Delhi,IT,4.5
18,120,Rohit Bansal,36,980000.0,12.000000,Mumbai,Finance,4.9

In [52]:
df_new.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Salary (INR)          0
Experience (Years)    0
City                  0
Department            0
Performance Rating    0
dtype: int64